spring:
  application:
    name: voicecal-agent
  profiles:
    active: h2
  jpa:
    open-in-view: false

server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
